name: "Pipeline: Test, Lint, Build"
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  go-lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    container: deluan/ci-goreleaser:1.23.0-1
    steps:
      - uses: actions/checkout@v4

      - name: Config workspace folder as trusted
        run: git config --global --add safe.directory $GITHUB_WORKSPACE;  git describe --dirty --always --tags

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          problem-matchers: true
          args: --timeout 2m

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - run: goimports -w `find . -name '*.go' | grep -v '_gen.go$'`
      - run: go mod tidy
      - name: Verify no changes from goimports and go mod tidy
        run: |
          git status --porcelain
          if [ -n "$(git status --porcelain)" ]; then
            echo 'To fix this check, run "make format" and commit the changes'
            exit 1
          fi

  go:
    name: Test Go code
    runs-on: ubuntu-latest
    container: deluan/ci-goreleaser:1.23.0-1
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Config workspace folder as trusted
        run: git config --global --add safe.directory $GITHUB_WORKSPACE;  git describe --dirty --always --tags

      - name: Download dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        continue-on-error: ${{contains(matrix.go_version, 'beta') || contains(matrix.go_version, 'rc')}}
        run: go mod download

      - name: Test
        continue-on-error: ${{contains(matrix.go_version, 'beta') || contains(matrix.go_version, 'rc')}}
        run: go test -shuffle=on -race -cover ./... -v

  js:
    name: Build JS bundle
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: npm install dependencies
        run: |
          cd ui
          npm ci

      - name: npm lint
        run: |
          cd ui
          npm run check-formatting && npm run lint

      - name: npm test
        run: |
          cd ui
          npm test

      - name: npm build
        run: |
          cd ui
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: js-bundle
          path: ui/build
          retention-days: 7
  i18n-lint:
    name: Lint i18n files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e
          for file in resources/i18n/*.json; do
            echo "Validating $file"
            if ! jq empty "$file" 2>error.log; then
              error_message=$(cat error.log)
              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
              echo "::error file=$file,line=$line_number::$error_message"
              exit 1
            fi
          done

  binaries:
    name: Build binaries
    needs: [js]
    runs-on: ubuntu-latest
    container: deluan/ci-goreleaser:1.23.0-1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config workspace folder as trusted
        run: git config --global --add safe.directory $GITHUB_WORKSPACE;  git describe --dirty --always --tags

      - uses: actions/download-artifact@v4
        with:
          name: js-bundle
          path: ui/build

      - name: Run GoReleaser - SNAPSHOT
        if: startsWith(github.ref, 'refs/tags/') != true
        run: goreleaser release --clean --skip=publish --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser - RELEASE
        if: startsWith(github.ref, 'refs/tags/')
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist
            !dist/*.tar.gz
            !dist/*.zip
          retention-days: 14

